name: "Pull Request Labeller"
on:
  pull_request_target:
    types:
      - closed
      - opened
      - reopened
      - synchronize
      - converted_to_draft
      - ready_for_review
      - review_requested
      - review_request_removed

jobs:
  label:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const prNumber = context.issue.number;
            const pull = await github.rest.pulls.get({
              owner: context.payload.repository.owner.login,
              repo: context.payload.repository.name,
              pull_number:  context.issue.number
            });
            await github.rest.issues.addLabels({
              owner: context.payload.repository.owner.login,
              repo: context.payload.repository.name,
              issue_number: context.issue.number,
              labels: ["spam"]
            )};
            await github.rest.pulls.update({
              owner: context.payload.repository.owner.login,
              repo: context.payload.repository.name,
              pull_number: context.payload.pull_request.number,
              state: "closed"
            });
